services:
  - type: web
    name: shruti-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      API_ID: 
        value: "34393873"
      API_HASH: 
        value: "d1b23d08b98afc02a89431c6960872b9"
      API_KEY:
        sync: false
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        value: "mongodb+srv://yacan69355:Cw92BrnfAfWQcLvU@cluster0.jh6h6wg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      OWNER_ID:
        value: "8018964088"
      OWNER_USERNAME:
        value: "https://t.me/BAN9T"
      BOT_USERNAME:
        value: 
      UPSTREAM_REPO:
        value: 
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1003605648205
      SUPPORT_GROUP:
        value: 
      SUPPORT_CHANNEL:
        value: https://t.me/BAN9T
      INSTAGRAM:
        value: 
      YOUTUBE:
        value: 
      GITHUB:
        value: 
      DONATE:
        value: 
      START_IMG_URL:
        sync: false
